defmodule Inkress.Orders do
  @moduledoc """
  Create orders on Inkress.

  ## Example

      client = Inkress.new(api_token: "…", merchant_username: "my-store")

      {:ok, order} =
        Inkress.Orders.create(client, %{
          currency_code: "JMD",
          total: 2999,
          customer: %{email: "a@b.com", first_name: "Jane", last_name: "Doe"},
          products: [%{id: 1, quantity: 2}],
          data: %{shipping_address: %{city: "Kingston", country: "JM"}}
        })
  """

  alias Inkress.{Client, Error, HTTP, Order}

  @orders_path "/api/v1/orders"

  @typedoc """
  Order parameters (atom keys). `:currency_code` is required by the API. `:kind`
  defaults to `"order"`. `:reference_id` is auto-generated by Inkress when omitted.
  Common keys: `:currency_code`, `:total`, `:title`, `:reference_id`, `:customer`,
  `:products`, `:data`.

  Each entry in `:products` is `%{id: ..., quantity: ...}` and may carry an explicit
  `:unit_price` for custom / quoted pricing — honored only for a **secret-key**
  (`sk_live_…`) client; otherwise the catalog price is used.
  """
  @type params :: %{optional(atom()) => term()}

  @doc """
  Create an order (`POST /api/v1/orders`).

  Returns `{:ok, %Inkress.Order{}}` on success, or `{:error, %Inkress.Error{}}`.
  """
  @spec create(Client.t(), params()) :: {:ok, Order.t()} | {:error, Error.t()}
  def create(%Client{} = client, params) when is_map(params) do
    body = Map.put_new(params, :kind, "order")

    case HTTP.post(client, @orders_path, body) do
      {:ok, order} when is_map(order) ->
        {:ok, Order.from_map(order)}

      {:ok, _unexpected} ->
        {:error, Error.new(message: "unexpected response: order payload missing")}

      {:error, %Error{}} = error ->
        error
    end
  end

  @doc """
  Create an **open-amount** order — a charge for an arbitrary `:total` with no
  catalog product lines (e.g. a quoted price, a service, a custom invoice amount).

  Requires a positive `:total` and rejects `:products` (line items go through
  `create/2`). Common keys: `:currency_code`, `:total`, `:title`, `:customer`,
  `:reference_id`. The amount is validated client-side before any request, and is
  still subject to the API's per-currency minimums.
  """
  @spec create_open_amount(Client.t(), params()) :: {:ok, Order.t()} | {:error, Error.t()}
  def create_open_amount(%Client{} = client, params) when is_map(params) do
    cond do
      has_products?(params) ->
        {:error,
         Error.new(
           message: "create_open_amount/2 does not accept :products; use create/2 for line items"
         )}

      not positive_total?(params) ->
        {:error, Error.new(message: "open-amount orders require a positive :total")}

      true ->
        create(client, params)
    end
  end

  defp has_products?(params) do
    case Map.get(params, :products) do
      nil -> false
      [] -> false
      list when is_list(list) -> true
      _ -> false
    end
  end

  defp positive_total?(params) do
    case Map.get(params, :total) do
      total when is_number(total) and total > 0 -> true
      _ -> false
    end
  end
end
